//! The parts of the relay that are pure: what to answer when the app cannot be reached, and how to
//! find the id that answer has to echo.

/// A JSON-RPC error frame answering `request`, for when the app cannot be reached.
///
/// Echoes the request's id so the client can match it to what it sent: an error with a null id
/// leaves the call pending until the client times out, which reads as a hang rather than an
/// answer.
pub(crate) fn unavailable_frame(request: &str) -> String {
    format!(
        "{{\"jsonrpc\":\"2.0\",\"id\":{},\"error\":{{\"code\":-32000,\"message\":\
         \"Allodia Mail & Calendar is not running, or MCP access is off (Settings → Advanced).\"}}}}",
        request_id(request).unwrap_or_else(|| "null".to_owned()),
    )
}

/// Extracts the raw JSON text of a request's `id`, or `None`.
///
/// A deliberately small scanner rather than a JSON parser: this crate carries **no dependency at
/// all on Unix** (see its `Cargo.toml`), and pulling in `serde_json` to read one field would drag
/// a parser into a byte relay. The input is machine-generated by an MCP client's own serializer,
/// so a token scan is sound; anything it cannot read falls back to `null`, which is a worse
/// answer but never a wrong one.
pub(crate) fn request_id(request: &str) -> Option<String> {
    let start = request.find("\"id\"")? + "\"id\"".len();
    let rest = request[start..].trim_start();
    let rest = rest.strip_prefix(':')?.trim_start();
    let mut chars = rest.char_indices();
    match chars.next()? {
        // A string id: copy through to the closing quote, honouring backslash escapes.
        (_, '"') => {
            let mut escaped = false;
            for (index, ch) in chars {
                if escaped {
                    escaped = false;
                } else if ch == '\\' {
                    escaped = true;
                } else if ch == '"' {
                    return Some(rest[..=index].to_owned());
                }
            }
            None
        }
        // A numeric id, or the literal `null`.
        (_, first) if first.is_ascii_digit() || first == '-' => {
            let end = rest
                .find(|ch: char| !(ch.is_ascii_digit() || ch == '-' || ch == '.'))
                .unwrap_or(rest.len());
            Some(rest[..end].to_owned())
        }
        _ if rest.starts_with("null") => Some("null".to_owned()),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::request_id;

    #[test]
    fn a_numeric_id_is_echoed_so_the_client_can_match_the_error_to_its_call() {
        // Without this the client's request stays pending until it times out, which reads as a
        // hang rather than "the app is not running".
        assert_eq!(
            request_id(r#"{"jsonrpc":"2.0","id":7,"method":"tools/list"}"#).as_deref(),
            Some("7"),
        );
    }

    #[test]
    fn a_string_id_survives_quoting_and_escapes() {
        assert_eq!(
            request_id(r#"{"id":"call-1","method":"ping"}"#).as_deref(),
            Some(r#""call-1""#),
        );
        assert_eq!(
            request_id(r#"{"id":"a\"b","method":"ping"}"#).as_deref(),
            Some(r#""a\"b""#),
        );
    }

    #[test]
    fn whitespace_between_the_key_and_the_value_is_tolerated() {
        assert_eq!(
            request_id("{ \"id\" : 42 , \"method\": \"ping\" }").as_deref(),
            Some("42"),
        );
    }

    #[test]
    fn an_unreadable_id_falls_back_rather_than_guessing() {
        assert_eq!(
            request_id(r#"{"method":"notifications/initialized"}"#),
            None
        );
        assert_eq!(request_id(r#"{"id":{"nested":1}}"#), None);
    }
}
