#!/usr/bin/env bash
# Android client build: cross-compile the cdylib -> generate Kotlin bindings ->
# Gradle APK -> install + run on a connected device/emulator. Mirrors ../macos/build-and-run.sh.
# (A real Android Studio project is the next step; this proves the binding renders.)
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)" # the repository root

# --- SDK / NDK locations -----------------------------------------------------
export ANDROID_HOME="${ANDROID_HOME:-$HOME/Library/Android/sdk}"
NDK_DIR="$(ls -d "$ANDROID_HOME/ndk/"*/ 2>/dev/null | sort -V | tail -1)"
export ANDROID_NDK_HOME="${ANDROID_NDK_HOME:-${NDK_DIR%/}}"
ADB="$ANDROID_HOME/platform-tools/adb"
# Both ABIs the APK ships, so this loop works on an arm64 device/AVD *and* an x86_64 emulator.
# It has to match `defaultConfig.ndk.abiFilters` in app/build.gradle.kts exactly: Gradle packages
# every ABI in that filter, so one we skip here yields an APK that installs on such a device and
# then dies at the first `System.loadLibrary`.
ABIS=(arm64-v8a x86_64)
RUST_TARGETS=(aarch64-linux-android x86_64-linux-android)
# The installed package name follows the brand (docs/branding.md), so it is read rather than
# written here: an unbranded build installs under a different id, and a script holding this one
# would install fine and then launch nothing.
# shellcheck source=scripts/dev/brand.sh
. "$ROOT/scripts/dev/brand.sh"
brand_load
PKG="$MAILCAL_APP_ID"

echo "==> Cross-compiling the cdylib for ${ABIS[*]} (cargo-ndk, NDK: $ANDROID_NDK_HOME)"
command -v cargo-ndk >/dev/null 2>&1 || cargo install cargo-ndk
# rustup installs a pinned toolchain (rust-toolchain.toml) with the host target only, so the first
# Android build after a toolchain bump fails deep in a dependency with "can't find crate for `core`".
# Idempotent, and a no-op once the targets are present.
rustup target add "${RUST_TARGETS[@]}" >/dev/null
# `dev-harness` compiles the dev-only custom-root TLS path into this release core, so the debug
# APK can drive the local Stalwart harness over IMAP (--account stalwart-imap). It stays inert
# unless MAILCAL_EXTRA_CA is set at runtime, and a production release build omits the feature.
#
# The Allodia sign-in rides along when this build was given the registration that turns it on --
# derived from that registration rather than asked for separately, so the two halves cannot
# disagree (scripts/dev/lib.sh, BUILDING.md). It resolves to nothing in a build from source.
# shellcheck source=scripts/dev/lib.sh
. "$ROOT/scripts/dev/lib.sh"
CORE_FEATURES="dev-harness"
ALLODIA_FEATURE="$(core_cargo_features)"
if [ -n "$ALLODIA_FEATURE" ]; then
  CORE_FEATURES="$CORE_FEATURES,$ALLODIA_FEATURE"
fi
NDK_ABI_ARGS=()
for abi in "${ABIS[@]}"; do NDK_ABI_ARGS+=(-t "$abi"); done
(cd "$ROOT" && cargo ndk "${NDK_ABI_ARGS[@]}" -o "$HERE/app/src/main/jniLibs" build -p mailcal-bindings --release --features "$CORE_FEATURES")

# The Kotlin binding + the localised resources are generated by Gradle itself (see the
# "Generated sources" block in app/build.gradle.kts), so every entry point, this script, Android
# Studio, `./gradlew :app:test`, and CI, regenerates them from one definition instead of each
# remembering to. Nothing to do here.

# The shared composer editor is packaged straight out of clients/composer/dist (an asset directory
# in app/build.gradle.kts), and the bundle there is committed rather than generated per build, so
# rebuild it from its TypeScript sources before Gradle copies it into the APK.
bash "$ROOT/scripts/dev/composer-bundle.sh"

echo "==> Assembling the APK"
(cd "$HERE" && ./gradlew --quiet :app:assembleDebug)
APK="$HERE/app/build/outputs/apk/debug/app-debug.apk"

echo "==> Installing + launching on the device/emulator"
"$ADB" wait-for-device
if [[ "${MAILCAL_DEV_ACCOUNT:-}" == "stalwart" || "${MAILCAL_DEV_ACCOUNT:-}" == "stalwart-multi" || "${MAILCAL_DEV_ACCOUNT:-}" == "stalwart-imap" ]]; then
  echo "==> Mapping Android localhost to the host Stalwart harness (adb reverse)"
  "$ADB" reverse tcp:28080 tcp:28080
  if [[ "${MAILCAL_DEV_ACCOUNT:-}" == "stalwart-imap" ]]; then
    "$ADB" reverse tcp:12993 tcp:12993
    # SMTP submission (STARTTLS). The stalwart-imap fixture carries an [smtp] and a [caldav]
    # half so it is mail-beside-a-separate-calendar, the shape meeting invitations break on
    # (docs/invitations.md); CalDAV rides 28080, already reversed above.
    "$ADB" reverse tcp:12587 tcp:12587
  fi
fi
# `-d` allows a version-code downgrade. The APK is versioned from VERSION, so any box that has
# run a newer build than the branch under test, a release build, or simply a newer branch:
# refuses the install outright, and the obvious way out (`adb uninstall`) takes the accounts and
# store with it. Debug-signed builds only, which is all this script ever installs.
"$ADB" install -r -d "$APK"
echo "==> Logs (on device): /data/data/$PKG/files/logs/app.log (rotates .1-.3, ~4 MB cap)"
echo "    Read them: \"$ADB\" exec-out run-as $PKG cat files/logs/app.log"
# A dev-account override (e.g. MAILCAL_DEV_ACCOUNT=stalwart, targeting the local Stalwart harness)
# rides in as a string intent extra the debug build reads at launch; unset in normal use, so the
# stored personal accounts are used. install -r above replaced the app, so this is a fresh onCreate.
START_EXTRAS=()
if [[ -n "${MAILCAL_DEV_ACCOUNT:-}" ]]; then
  echo "==> Launching with MAILCAL_DEV_ACCOUNT=$MAILCAL_DEV_ACCOUNT"
  START_EXTRAS+=(-e MAILCAL_DEV_ACCOUNT "$MAILCAL_DEV_ACCOUNT")
  # The IMAP dev account (stalwart-imap) needs the harness's self-signed cert trusted; it rides in
  # base64 (env vars can't be set via am start, so the app writes it and calls Os.setenv).
  [[ -n "${MAILCAL_EXTRA_CA_PEM:-}" ]] && START_EXTRAS+=(-e MAILCAL_EXTRA_CA_PEM "$MAILCAL_EXTRA_CA_PEM")
fi
# A showcase (screenshot) run boots the seeded in-memory dataset instead of any account, and names
# the language to seed it in and the screen to drive to. Same intent-extra channel as the dev account.
if [[ -n "${MAILCAL_SHOWCASE:-}" ]]; then
  echo "==> Launching with MAILCAL_SHOWCASE=$MAILCAL_SHOWCASE"
  START_EXTRAS+=(-e MAILCAL_SHOWCASE "$MAILCAL_SHOWCASE")
  [[ -n "${MAILCAL_SHOWCASE_SCREEN:-}" ]] && START_EXTRAS+=(-e MAILCAL_SHOWCASE_SCREEN "$MAILCAL_SHOWCASE_SCREEN")
fi
# Which light/dark appearance to come up in, for a screenshot or a UI check that must not depend on
# how the device happens to be set. Independent of the two above, so it applies to any launch.
if [[ -n "${MAILCAL_APPEARANCE:-}" ]]; then
  echo "==> Launching with MAILCAL_APPEARANCE=$MAILCAL_APPEARANCE"
  START_EXTRAS+=(-e MAILCAL_APPEARANCE "$MAILCAL_APPEARANCE")
fi
"$ADB" shell am start -n "$PKG/.MainActivity" ${START_EXTRAS[@]+"${START_EXTRAS[@]}"} >/dev/null
sleep 4

echo "==> Capturing screenshot + the round-trip log line"
"$ADB" exec-out screencap -p >"$HERE/screenshot.png"
"$ADB" logcat -d -s Mailcal | tail -3
echo "==> Done. Screenshot: $HERE/screenshot.png"
