#!/usr/bin/env bash
# Derive the Android launcher icon from the one brand source.
#
# The twin of clients/apple/Scripts/generate-appicon.sh, clients/linux/flatpak/generate-icons.sh and
# clients/windows/Mailcal/Images/generate-assets.ps1, same source icon, and
# scripts/dev/brand-icons.sh runs whichever of the four this host can.
#
#   clients/android/generate-icons.sh [path/to/source.png]
#
# An adaptive icon is THREE layers, not one image, and each has a rule the others do not:
#
#   background  Fills the whole 108dp canvas. Only ever seen at the edges, while the launcher
#               parallaxes the layers against each other. A flat colour sampled from the art, so a
#               reveal has nothing to reveal.
#   foreground  Also 108dp, but the launcher's mask is applied to the inner 72dp, the outer 18dp
#               on each side exists to be slid out of view. Full-bleed art therefore has to cover
#               MORE than the viewport or a parallax shift walks a straight seam across the icon,
#               and less than the canvas or it is cropped to its middle two thirds. 84dp splits it:
#               the viewport is covered with 6dp to spare, at the cost of 7% off each edge.
#
# There is a third layer, `<monochrome>`, for Android 13+ themed icons, see "Known gaps" in
# docs/branding.md for why this does not write one.
#
# It writes no raster mipmap. `mipmap-*/<icon>.webp` and its circle-cropped `_round` twin are the
# API 25 and below fallback, and minSdk is 31, `aapt2 dump badging` resolves the manifest's icon to
# the adaptive XML at every density bucket, so an APK built without them is byte-for-byte as
# capable. The `_round` half was doubly dead: a round icon is only ever read through
# `android:roundIcon`, which the manifest does not declare.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"          # clients/android
ROOT="$(cd "$HERE/../.." && pwd)"              # repo root (worktree)
# shellcheck source=scripts/dev/lib.sh
. "$ROOT/scripts/dev/lib.sh"   # brand_icon_source + imagemagick_bin
SRC="${1:-$(brand_icon_source)}"
RES="$HERE/app/src/main/res"
NAME="allodia_mailcal_icon"                    # the resource name the manifest points at

IM="$(imagemagick_bin || true)"
if [[ -z "$IM" ]]; then
  echo "generate-icons: need ImageMagick (brew install imagemagick)" >&2
  exit 1
fi
im() { "$IM" "$@"; }

if [[ ! -f "$SRC" ]]; then
  echo "generate-icons: source not found: $SRC" >&2
  exit 1
fi

echo "==> Source icon: $SRC"

# The background colour is read OUT of the art rather than written down beside it, so a new source
# icon cannot leave a stale colour behind. The sample is the mean of the four corners: on a
# full-bleed icon those are background by construction, and averaging four of them keeps a corner
# that happens to catch a highlight from deciding the whole layer.
corner_mean() { # -> #rrggbb
  local px=() c
  local w h
  w="$(im "$SRC" -format '%w' info:)"
  h="$(im "$SRC" -format '%h' info:)"
  for c in "0,0" "$((w - 1)),0" "0,$((h - 1))" "$((w - 1)),$((h - 1))"; do
    px+=( "$(im "$SRC" -crop "1x1+${c%%,*}+${c##*,}" +repage -depth 8 -format '%[hex:u]' info:)" )
  done
  # `-alpha off` before reading the hex: with an alpha channel present ImageMagick prints RRGGBBAA,
  # and Android reads a leading pair as the ALPHA, an opaque blue would land as a transparent one.
  im -size 2x2 xc:none \
    -draw "fill #${px[0]} point 0,0" -draw "fill #${px[1]} point 1,0" \
    -draw "fill #${px[2]} point 0,1" -draw "fill #${px[3]} point 1,1" \
    -resize 1x1 -alpha off -depth 8 -format '#%[hex:u]' info:
}

BG="$(corner_mean)"
echo "==> Background colour sampled from the source corners: $BG"

# The background layer is a vector so it costs one file at every density and stays crisp when the
# launcher scales it. Written from the sampled colour rather than kept by hand.
cat >"$RES/drawable/${NAME}_background.xml" <<XML
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by clients/android/generate-icons.sh from the brand source icon. Do not edit. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:fillColor="$BG"
        android:pathData="M0,0h108v108h-108z" />
</vector>
XML

cat >"$RES/mipmap-anydpi-v26/${NAME}.xml" <<XML
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by clients/android/generate-icons.sh from the brand source icon. Do not edit. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/${NAME}_background" />
    <foreground android:drawable="@mipmap/${NAME}_foreground" />
</adaptive-icon>
XML

# Lossy webp at q90 with lossless alpha, the same trade scripts/dev/brand-welcome.sh explains for
# the welcome art, and for the same reason: flat shapes over smooth gradients are the worst case for
# lossless, and the alpha edge is what has to stay crisp.
webp() { # <source args…> <out>
  local out="${*: -1}"
  im "${@:1:$#-1}" -strip -quality 90 -define webp:method=6 -define webp:alpha-quality=100 "$out"
}

# The 108dp adaptive canvas in each density bucket's pixels: 1x, 1.5x, 2x, 3x, 4x.
for pair in mdpi:108 hdpi:162 xhdpi:216 xxhdpi:324 xxxhdpi:432; do
  bucket="${pair%%:*}"; layer="${pair##*:}"
  out="$RES/mipmap-$bucket"
  mkdir -p "$out"

  art=$(( layer * 7 / 9 ))     # 84dp of the 108, for the reason in the header

  webp "$SRC" -resize "${art}x${art}" \
    -background none -gravity center -extent "${layer}x${layer}" \
    "$out/${NAME}_foreground.webp"
done

# Play wants a 512x512 32-bit PNG for the listing. It is not read at runtime and not packaged.
im "$SRC" -resize 512x512 -strip "$HERE/app/src/main/${NAME}-playstore.png"

echo "==> Wrote the adaptive icon (background + foreground) and the 512 Play listing icon"
