package eu.allodia.mailcal

import android.content.Context
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.drawable.AdaptiveIconDrawable
import android.graphics.drawable.Drawable
import androidx.core.content.res.ResourcesCompat
import androidx.test.core.app.ApplicationProvider
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.GraphicsMode

/**
 * The launcher icon is three separate layers with three different rules, generated by
 * `clients/android/generate-icons.sh` from the one brand source (docs/branding.md). Getting a layer
 * wrong is invisible to every other gate: the app builds, installs and runs, and the mistake is on
 * the home screen of whoever installed it.
 *
 * These assert the layers' contract, never the art, an unbranded build has to pass them too.
 */
@GraphicsMode(GraphicsMode.Mode.NATIVE)
@RunWith(RobolectricTestRunner::class)
class LauncherIconTest {
    private val context: Context = ApplicationProvider.getApplicationContext()

    /** An adaptive icon is authored on a 108dp canvas. 2px per dp is enough to read a corner from. */
    private val canvas = 216
    private val viewport = canvas * 2 / 3        // …of which the launcher's mask shows the inner 72dp
    private val viewportOrigin = (canvas - viewport) / 2

    private fun launcherIcon(): AdaptiveIconDrawable {
        // Through the manifest rather than R.mipmap directly: what ships is the icon the manifest
        // names, and a test that reaches past it would pass on an icon nothing installs.
        val icon = ResourcesCompat.getDrawable(context.resources, context.applicationInfo.icon, null)
        assertTrue(
            "the manifest's android:icon is ${icon?.javaClass?.simpleName}, not an adaptive icon",
            icon is AdaptiveIconDrawable,
        )
        return icon as AdaptiveIconDrawable
    }

    private fun render(drawable: Drawable): Bitmap {
        val bitmap = Bitmap.createBitmap(canvas, canvas, Bitmap.Config.ARGB_8888)
        drawable.setBounds(0, 0, canvas, canvas)
        drawable.draw(Canvas(bitmap))
        return bitmap
    }

    @Test
    fun the_background_layer_is_this_app_s_own_and_covers_the_canvas() {
        val background = render(launcherIcon().background)

        // Android Studio's new-project template. It is a placeholder nobody chose, and shipping it
        // is what this assertion is here to catch: it is not obviously wrong in a diff, and it only
        // ever appears in the sliver of background a launcher's parallax uncovers.
        val template = 0xFF3DDC84.toInt()
        // Corners AND centre: the template is a green field with a white grid, so a sample that
        // happened to land on a grid line would read as "not green".
        val samples = listOf(
            0 to 0, canvas - 1 to 0, 0 to canvas - 1, canvas - 1 to canvas - 1, canvas / 2 to canvas / 2,
        )
        samples.forEach { (x, y) ->
            val pixel = background.getPixel(x, y)
            assertEquals(
                "the background layer is transparent at ($x, $y); a launcher would show the wallpaper",
                0xFF,
                pixel ushr 24,
            )
            assertTrue(
                "the background layer is still Android Studio's placeholder green",
                pixel != template,
            )
        }
    }

    @Test
    fun the_foreground_layer_covers_the_whole_masked_viewport() {
        val foreground = render(launcherIcon().foreground)

        // Full-bleed art has to reach past the viewport on every side, or the launcher's parallax
        // walks a straight seam of background across the icon while the user scrolls.
        for (x in viewportOrigin until viewportOrigin + viewport) {
            for (y in viewportOrigin until viewportOrigin + viewport) {
                if (foreground.getPixel(x, y) ushr 24 != 0xFF) {
                    throw AssertionError(
                        "the foreground layer is not opaque at ($x, $y) of a ${canvas}px canvas, " +
                            "so the masked viewport shows background through the art",
                    )
                }
            }
        }
    }

    @Test
    fun a_themed_icon_is_a_silhouette_or_is_not_offered() {
        // Android 13+ throws the monochrome layer's colours away and tints its ALPHA with one
        // colour from the wallpaper palette. Handed the full-colour art, whose alpha is a solid
        // rectangle, it paints a featureless slab, and the app loses its mark entirely on every
        // home screen with themed icons switched on. No layer at all is the better failure: the
        // launcher then falls back to this icon, in colour.
        val monochrome = launcherIcon().monochrome ?: return

        val rendered = render(monochrome)
        val opaqueColours = mutableSetOf<Int>()
        for (x in 0 until canvas step 4) {
            for (y in 0 until canvas step 4) {
                val pixel = rendered.getPixel(x, y)
                if (pixel ushr 24 > 0x80) opaqueColours += pixel and 0x00FFFFFF
            }
        }
        assertTrue(
            "the monochrome layer draws ${opaqueColours.size} colours, so it is artwork rather " +
                "than a silhouette, a themed launcher will render it as one flat shape",
            opaqueColours.size <= 1,
        )
    }
}
