//! Emits WinUI 3 resources (`Strings/<locale>/Resources.resw`) plus a typed `L10n.cs`
//! accessor. `{name}` placeholders become `string.Format` positional holes (`{0}`, `{1}`),
//! indexed by the base template's placeholder order. The Windows App SDK resource compiler
//! turns the `.resw` files into a `resources.pri`; the accessor resolves them through an
//! MRT-Core `ResourceManager` whose `ResourceContext` language qualifier `L10n.SetLanguage`
//! overrides, which, unlike `ApplicationLanguages.PrimaryLanguageOverride`, needs no package
//! identity and so works in the unpackaged build too.

use crate::{
    brand::Brand,
    model::{Catalog, Message, ParamType, param_type, pascal_case},
};

/// Renders the `.resw` files and the C# accessor as `(relative_path, content)` entries,
/// rooted at the WinUI project directory.
#[must_use]
pub(crate) fn render(catalog: &Catalog, namespace: &str, brand: &Brand) -> Vec<(String, String)> {
    let mut files = Vec::new();
    for loc in &catalog.locales {
        files.push((
            format!("Strings/{loc}/Resources.resw"),
            render_resw(catalog, loc),
        ));
    }
    files.push(("L10n.cs".to_string(), render_accessor(catalog, namespace)));
    files.push((
        "L10nLocales.cs".to_string(),
        render_locales_file(catalog, namespace),
    ));
    files.push(("Brand.cs".to_string(), render_brand_file(namespace, brand)));
    files
}

/// The application id this build was branded with (`docs/branding.md`), as a dependency-free
/// class for the same reason `L10nLocales.cs` is one: `Mailcal.Tests` is a plain `net10.0`
/// assembly and cannot link anything that touches WinUI, yet the protocol scheme, the credential
/// target prefix and the MCP pipe name are exactly the kind of thing a test must pin.
///
/// Windows takes it as a constant rather than asking the platform because the dev loop runs
/// **unpackaged**, where `Package.Current` throws: so the one answer available at runtime is
/// unavailable in half the builds.
fn render_brand_file(namespace: &str, brand: &Brand) -> String {
    format!(
        "// GENERATED by mailcal-l10n; do not edit.\n\
         \n\
         namespace {namespace};\n\
         \n\
         /// <summary>\n\
         /// What the operating system knows this build by.\n\
         /// </summary>\n\
         internal static class Brand\n\
         {{\n\
         \x20   /// <summary>\n\
         \x20   /// The reverse-DNS application id: the MSIX package name, the custom URI scheme\n\
         \x20   /// every browser sign-in redirects back to, the credential target prefix, and the\n\
         \x20   /// MCP named pipe. Lowercase by rule.\n\
         \x20   /// </summary>\n\
         \x20   public const string AppId = \"{id}\";\n\
         }}\n",
        id = brand.id
    )
}

fn render_resw(catalog: &Catalog, loc: &str) -> String {
    let mut out = String::new();
    out.push_str(RESW_HEADER);
    for message in &catalog.messages {
        if let Some(value) = message.values.get(loc) {
            out.push_str("  <data name=\"");
            out.push_str(&message.key);
            out.push_str("\" xml:space=\"preserve\">\n    <value>");
            out.push_str(&winui_value(value, &message.placeholders));
            out.push_str("</value>\n  </data>\n");
        }
    }
    out.push_str("</root>\n");
    out
}

/// Rewrites `{name}` into `string.Format` holes (`{0}`, `{1}`, …) and XML-escapes the literal
/// text. Literal braces are doubled (`{{` / `}}`) only in messages with format args, since the
/// accessor only calls `string.Format` then.
fn winui_value(template: &str, placeholders: &[String]) -> String {
    let formatted = !placeholders.is_empty();
    let mut out = String::new();
    let mut rest = template;
    while let Some(open) = rest.find('{') {
        push_winui_text(&mut out, &rest[..open], formatted);
        let after = &rest[open + 1..];
        if let Some(close) = after.find('}') {
            let name = &after[..close];
            if let Some(idx) = placeholders.iter().position(|p| p == name) {
                out.push('{');
                out.push_str(&idx.to_string());
                out.push('}');
            } else {
                push_winui_text(&mut out, &rest[open..=open + 1 + close], formatted);
            }
            rest = &after[close + 1..];
        } else {
            push_winui_text(&mut out, &rest[open..], formatted);
            return out;
        }
    }
    push_winui_text(&mut out, rest, formatted);
    out
}

fn push_winui_text(out: &mut String, text: &str, formatted: bool) {
    for c in text.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '{' if formatted => out.push_str("{{"),
            '}' if formatted => out.push_str("}}"),
            _ => out.push(c),
        }
    }
}

fn render_accessor(catalog: &Catalog, namespace: &str) -> String {
    let mut out = ACCESSOR_HEADER.replace("{NAMESPACE}", namespace);
    for message in &catalog.messages {
        out.push_str(&accessor_member(message));
    }
    out.push_str(&render_locales(catalog));
    out.push_str("}\n");
    out
}

/// The endonym lookup, so the language picker labels each row in its own tongue. Resource-backed,
/// so it belongs with the rest of the MRT-Core accessor, the bare locale *list* does not, and is
/// emitted separately by [`render_locales_file`].
fn render_locales(_catalog: &Catalog) -> String {
    "\n    /// <summary>\n\
     \x20   /// The endonym for a shipped locale (\"Nederlands\" for \"nl\"); its\n\
     \x20   /// settings_language_&lt;code&gt; message. An unknown code yields the code itself.\n\
     \x20   /// </summary>\n\
     \x20   public static string LanguageName(string code) => Get(\"settings_language_\" + code);\n"
        .to_string()
}

/// The catalog's locale list, as a **second, dependency-free** partial of the same class.
///
/// It is split out because the list is plain data while the rest of `L10n` is MRT-Core resource
/// plumbing, and the two have different audiences. `AppCulture` maps a language choice onto a
/// formatting culture and must accept exactly the shipped locales, but it is deliberately
/// WinUI-free so `Mailcal.Tests` (a plain `net10.0` assembly, no Windows TFM) can pin it. Linking
/// the resource-backed half there fails to compile on
/// `Microsoft.Windows.ApplicationModel.Resources`. So the list lives where both can reach it, and
/// the alternative (a hand-kept locale array beside the catalog's) is exactly the drift this
/// crate exists to prevent.
fn render_locales_file(catalog: &Catalog, namespace: &str) -> String {
    let list = catalog
        .locales
        .iter()
        .map(|l| format!("\"{l}\""))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "// GENERATED by mailcal-l10n; do not edit.\n\
         \n\
         namespace {namespace};\n\
         \n\
         /// <summary>\n\
         /// The shipped locale list: the dependency-free half of <see cref=\"L10n\"/>, so code that\n\
         /// only needs to know *which* languages exist (and its tests) need not reference MRT-Core.\n\
         /// </summary>\n\
         internal static partial class L10n\n\
         {{\n\
         \x20   /// <summary>\n\
         \x20   /// The locales the app ships, in catalog order: the language picker's source of\n\
         \x20   /// truth, so adding one to the catalog adds it to the picker.\n\
         \x20   /// </summary>\n\
         \x20   public static readonly string[] Locales = [{list}];\n\
         }}\n"
    )
}

fn accessor_member(message: &Message) -> String {
    let name = pascal_case(&message.key);
    if message.placeholders.is_empty() {
        return format!(
            "    public static string {name}() => Get(\"{key}\");\n",
            key = message.key,
        );
    }
    let params = message
        .placeholders
        .iter()
        .map(|p| format!("{} {p}", csharp_type(param_type(p))))
        .collect::<Vec<_>>()
        .join(", ");
    let args = message.placeholders.join(", ");
    format!(
        "    public static string {name}({params}) => string.Format(Get(\"{key}\"), {args});\n",
        key = message.key,
    )
}

/// The accessor preamble: the MRT-Core resolution plumbing shared by every typed member. A
/// single `ResourceManager` (the app's `resources.pri`), the `Resources` subtree (where the
/// `.resw` data lands), and a mutable `ResourceContext` whose `Language` qualifier
/// [`SetLanguage`](#) overrides. `{NAMESPACE}` is substituted with the C# namespace; the typed
/// members and the closing brace are appended by [`render_accessor`].
const ACCESSOR_HEADER: &str = r#"// GENERATED by mailcal-l10n; do not edit.
using Microsoft.Windows.ApplicationModel.Resources;

namespace {NAMESPACE};

/// <summary>Typed access to the localised UI strings (Strings/*/Resources.resw).</summary>
internal static partial class L10n
{
    private static readonly ResourceManager Manager = new();
    private static readonly ResourceMap Map = Manager.MainResourceMap.GetSubtree("Resources");
    private static ResourceContext _context = Manager.CreateResourceContext();

    /// <summary>
    /// Overrides the language used for strings resolved afterwards: the empty string follows the
    /// OS, else a BCP-47 tag (e.g. "nl"). Unlike ApplicationLanguages.PrimaryLanguageOverride this
    /// needs no package identity, so it works in the unpackaged build. Call before any window
    /// loads; already-rendered x:Bind text does not re-resolve, so persist the choice and restart
    /// to switch a running app.
    /// </summary>
    public static void SetLanguage(string language)
    {
        // A fresh context defaults to the OS language; pin the qualifier only for an explicit choice.
        var context = Manager.CreateResourceContext();
        if (!string.IsNullOrEmpty(language))
        {
            context.QualifierValues["Language"] = language;
        }
        _context = context;
    }

    private static string Get(string key) => Map.TryGetValue(key, _context)?.ValueAsString ?? key;

"#;

fn csharp_type(t: ParamType) -> &'static str {
    match t {
        ParamType::Int => "int",
        ParamType::Str => "string",
    }
}

/// The canonical ResX/ResW preamble (schema + the four required resheaders). Data entries and
/// the closing `</root>` are appended by [`render_resw`].
const RESW_HEADER: &str = r#"<?xml version="1.0" encoding="utf-8"?>
<root>
  <!-- GENERATED by mailcal-l10n; do not edit. Source: messages/*.json -->
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" />
              </xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string" />
              <xsd:attribute name="name" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
"#;
