//! Emits `L10n.swift`: a typed accessor `enum` with the per-locale tables embedded, which
//! resolves the active locale from `Locale.preferredLanguages` (so it honours a per-app
//! `AppleLanguages` override and otherwise follows the OS language). The tables are embedded
//! rather than loaded from `.strings`/`.xcstrings` so the generated Swift needs no resource
//! bundle at runtime; it resolves the same inside the `MailcalKit` package as in the app
//! target. The accessor API is identical to a String-Catalog-backed one, so only this emitter
//! would change if that is ever wanted.

use crate::{
    brand::Brand,
    model::{Catalog, ParamType, param_type},
};

const HEADER: &str = "// GENERATED by mailcal-l10n; do not edit. Source: messages/*.json\n\n";

/// Renders the Swift sources as `(relative_path, content)` entries.
#[must_use]
pub(crate) fn render(catalog: &Catalog, brand: &Brand) -> Vec<(String, String)> {
    vec![
        ("L10n.swift".to_owned(), render_accessor(catalog)),
        ("Brand.swift".to_owned(), render_brand(brand)),
    ]
}

/// The application id this build was branded with (`docs/branding.md`).
///
/// `Bundle.main.bundleIdentifier` is the truer answer inside a running app, but `MailcalKit` is
/// also compiled and tested by SwiftPM outside any app bundle, where `Bundle.main` is the test
/// runner: so the value the app group, the keychain service and the OAuth redirects are built
/// from would differ between `swift test` and the shipped app. A constant is the same in both.
fn render_brand(brand: &Brand) -> String {
    format!(
        "{HEADER}\
         import Foundation\n\
         \n\
         /// What the operating system knows this build by.\n\
         public enum Brand {{\n\
         \x20   /// The reverse-DNS bundle id: also the app group (`group.<id>`), the keychain\n\
         \x20   /// service, the background-refresh task id, and the URI scheme browser sign-ins\n\
         \x20   /// come back to. Lowercase by rule.\n\
         \x20   public static let appID = {:?}\n\
         }}\n",
        brand.id
    )
}

fn render_accessor(catalog: &Catalog) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    // `public` so the multi-module Apple Swift package (MailcalUI + the app shell) can use the
    // accessors across module boundaries; harmless to the single-module macOS/Android builds.
    out.push_str("import Foundation\n\npublic enum L10n {\n");

    for message in &catalog.messages {
        let params = message
            .placeholders
            .iter()
            .map(|p| format!("{p}: {}", swift_type(param_type(p))))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str("    public static func ");
        out.push_str(&message.key);
        out.push('(');
        out.push_str(&params);
        out.push_str(") -> String {\n        resolve(\"");
        out.push_str(&message.key);
        out.push_str("\", ");
        out.push_str(&swift_args(message));
        out.push_str(")\n    }\n");
    }

    out.push('\n');
    render_tables(catalog, &mut out);
    render_runtime(catalog, &mut out);
    out.push_str("}\n");
    out
}

fn swift_args(message: &crate::model::Message) -> String {
    if message.placeholders.is_empty() {
        return "[:]".to_string();
    }
    let pairs = message
        .placeholders
        .iter()
        .map(|p| match param_type(p) {
            ParamType::Int => format!("\"{p}\": String({p})"),
            ParamType::Str => format!("\"{p}\": {p}"),
        })
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{pairs}]")
}

fn render_tables(catalog: &Catalog, out: &mut String) {
    out.push_str("    private static let tables: [String: [String: String]] = [\n");
    for loc in &catalog.locales {
        out.push_str("        \"");
        out.push_str(loc);
        out.push_str("\": [\n");
        for message in &catalog.messages {
            if let Some(value) = message.values.get(loc) {
                out.push_str("            \"");
                out.push_str(&message.key);
                out.push_str("\": \"");
                out.push_str(&swift_escape(value));
                out.push_str("\",\n");
            }
        }
        out.push_str("        ],\n");
    }
    out.push_str("    ]\n");
}

fn render_runtime(catalog: &Catalog, out: &mut String) {
    let available = catalog
        .locales
        .iter()
        .map(|l| format!("\"{l}\""))
        .collect::<Vec<_>>()
        .join(", ");
    out.push_str("\n    private static let base = \"");
    out.push_str(&catalog.base);
    out.push_str(
        "\"\n\n    /// The locales the app ships, in catalog order: the language picker's\n",
    );
    out.push_str("    /// source of truth, so adding one to the catalog adds it to the picker.\n");
    out.push_str("    public static let locales = [");
    out.push_str(&available);
    out.push_str("]\n");
    out.push_str(RUNTIME);
}

fn swift_type(t: ParamType) -> &'static str {
    match t {
        ParamType::Int => "Int",
        ParamType::Str => "String",
    }
}

fn swift_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(c),
        }
    }
    out
}

const RUNTIME: &str = r#"
    /// The endonym for a shipped locale ("Nederlands" for "nl"); its `settings_language_<code>`
    /// message, which every locale carries (the catalog validator enforces it). An unknown code
    /// yields the code itself.
    public static func languageName(_ code: String) -> String {
        resolve("settings_language_" + code, [:])
    }

    /// The active locale: the first of the OS's preferred languages we ship, else the base.
    private static func current() -> String {
        for language in Locale.preferredLanguages {
            let lower = language.lowercased()
            for locale in locales where lower == locale || lower.hasPrefix(locale + "-") {
                return locale
            }
        }
        return base
    }

    /// The `Locale` to format dates and numbers against; derived from the language the strings
    /// above resolved to, so a Dutch app writes Dutch dates.
    ///
    /// `Locale.current` cannot serve: the bundle declares no `nl` localisation (this catalog is
    /// generated Swift, not `.lproj`), so the OS resolves the app to English however the language
    /// is overridden, and a Dutch build listed `Mon` and headed its calendar `Jul 2026`. Resolved
    /// once, which is exact rather than a cache: `AppleLanguages` is read at launch, and changing
    /// the language relaunches the app.
    public static let appLocale = Locale(identifier: current())

    private static func resolve(_ key: String, _ args: [String: String]) -> String {
        let table = tables[current()] ?? tables[base] ?? [:]
        var text = table[key] ?? tables[base]?[key] ?? key
        for (name, value) in args {
            text = text.replacingOccurrences(of: "{\(name)}", with: value)
        }
        return text
    }
"#;
