//! Emits Android resources (`res/values/strings.xml` for the base locale,
//! `res/values-<locale>/strings.xml` for the rest) plus a typed `L10n.kt` accessor. `{name}`
//! placeholders become Android positional format args (`%1$s` / `%1$d`), indexed by the base
//! template's placeholder order and reused for every locale, so a reordered translation still
//! binds each argument correctly. Gradle compiles the `res/` tree and selects by OS locale;
//! the typed accessor wraps `Context.getString`.

use crate::model::{Catalog, Message, ParamType, param_type};

/// Renders the Android resource files and the Kotlin accessor as `(relative_path, content)`
/// entries, rooted at the module's `src/main` directory.
#[must_use]
pub(crate) fn render(catalog: &Catalog, package: &str) -> Vec<(String, String)> {
    let mut files = Vec::new();
    for loc in &catalog.locales {
        let dir = if loc == &catalog.base {
            "res/values".to_string()
        } else {
            format!("res/values-{loc}")
        };
        files.push((format!("{dir}/strings.xml"), render_strings(catalog, loc)));
    }
    let pkg_path = package.replace('.', "/");
    files.push((
        format!("java/{pkg_path}/L10n.kt"),
        render_accessor(catalog, package),
    ));
    files
}

fn render_strings(catalog: &Catalog, loc: &str) -> String {
    let mut out = String::new();
    out.push_str("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
    out.push_str("<!-- GENERATED by mailcal-l10n; do not edit. -->\n<resources>\n");
    for message in &catalog.messages {
        if let Some(value) = message.values.get(loc) {
            out.push_str("    <string name=\"");
            out.push_str(&message.key);
            out.push_str("\">");
            out.push_str(&android_value(value, &message.placeholders));
            out.push_str("</string>\n");
        }
    }
    out.push_str("</resources>\n");
    out
}

/// Rewrites `{name}` into Android positional args and escapes the literal text. Literal `%`
/// is doubled only in messages that actually carry format args (Android only treats `%` as a
/// format directive then).
fn android_value(template: &str, placeholders: &[String]) -> String {
    let formatted = !placeholders.is_empty();
    let mut out = String::new();
    let mut rest = template;
    while let Some(open) = rest.find('{') {
        push_android_text(&mut out, &rest[..open], formatted);
        let after = &rest[open + 1..];
        if let Some(close) = after.find('}') {
            let name = &after[..close];
            if let Some(idx) = placeholders.iter().position(|p| p == name) {
                let conv = match param_type(name) {
                    ParamType::Int => 'd',
                    ParamType::Str => 's',
                };
                out.push('%');
                out.push_str(&(idx + 1).to_string());
                out.push('$');
                out.push(conv);
            } else {
                push_android_text(&mut out, &rest[open..=open + 1 + close], formatted);
            }
            rest = &after[close + 1..];
        } else {
            push_android_text(&mut out, &rest[open..], formatted);
            return out;
        }
    }
    push_android_text(&mut out, rest, formatted);
    out
}

fn push_android_text(out: &mut String, text: &str, formatted: bool) {
    for c in text.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '\'' => out.push_str("\\'"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '%' if formatted => out.push_str("%%"),
            _ => out.push(c),
        }
    }
}

fn render_accessor(catalog: &Catalog, package: &str) -> String {
    let mut out = String::new();
    out.push_str("// GENERATED by mailcal-l10n; do not edit.\n");
    out.push_str("package ");
    out.push_str(package);
    out.push_str("\n\nimport android.content.Context\n\nobject L10n {\n");
    for message in &catalog.messages {
        out.push_str(&accessor_fn(message));
    }
    out.push_str(&render_locales(catalog));
    out.push_str("}\n");
    out
}

/// The catalog's locale list plus the endonym lookup, so the language picker is driven by the
/// catalog rather than a hand-kept list. Android resolves strings by resource id, so the lookup
/// is a generated `when` over the typed accessors (no `getIdentifier` reflection).
fn render_locales(catalog: &Catalog) -> String {
    let list = catalog
        .locales
        .iter()
        .map(|l| format!("\"{l}\""))
        .collect::<Vec<_>>()
        .join(", ");
    let mut arms = String::new();
    for l in &catalog.locales {
        arms.push_str("        \"");
        arms.push_str(l);
        arms.push_str("\" -> settings_language_");
        arms.push_str(l);
        arms.push_str("(ctx)\n");
    }
    format!(
        "\n    // The locales the app ships, in catalog order: the language picker's source of\n\
         \x20   // truth, so adding one to the catalog adds it to the picker.\n\
         \x20   val LOCALES = listOf({list})\n\
         \n\
         \x20   // The endonym for a shipped locale (\"Nederlands\" for \"nl\"); an unknown code\n\
         \x20   // yields the code itself.\n\
         \x20   fun languageName(ctx: Context, code: String): String = when (code) {{\n\
         {arms}\
         \x20       else -> code\n\
         \x20   }}\n"
    )
}

fn accessor_fn(message: &Message) -> String {
    if message.placeholders.is_empty() {
        return format!(
            "    fun {key}(ctx: Context): String = ctx.getString(R.string.{key})\n",
            key = message.key,
        );
    }
    let params = message
        .placeholders
        .iter()
        .map(|p| format!("{p}: {}", kotlin_type(param_type(p))))
        .collect::<Vec<_>>()
        .join(", ");
    let args = message.placeholders.join(", ");
    format!(
        "    fun {key}(ctx: Context, {params}): String = ctx.getString(R.string.{key}, {args})\n",
        key = message.key,
    )
}

fn kotlin_type(t: ParamType) -> &'static str {
    match t {
        ParamType::Int => "Int",
        ParamType::Str => "String",
    }
}
