//! Emits the Linux client's typed Rust accessor with embedded locale tables.
//!
//! The generated module resolves the process locale once through `sys-locale`, reduces it to a
//! catalog locale, and exposes one typed function per message. It has no runtime file lookup, so a
//! packaged app cannot lose its translations.

use std::fmt::Write;

use crate::{
    brand::Brand,
    model::{Catalog, Message, ParamType, param_type},
};

/// Renders `l10n.rs`, rooted at the caller's output directory.
#[must_use]
pub(crate) fn render(catalog: &Catalog, brand: &Brand) -> Vec<(String, String)> {
    vec![("l10n.rs".to_owned(), render_accessor(catalog, brand))]
}

fn render_accessor(catalog: &Catalog, brand: &Brand) -> String {
    let mut out = String::from(
        "// GENERATED by mailcal-l10n; do not edit.\n\
         use std::sync::OnceLock;\n\n\
         static LOCALE_OVERRIDE: OnceLock<Option<String>> = OnceLock::new();\n\n\
         pub(crate) fn set_locale_override(locale: Option<&str>) {\n\
             let _ = LOCALE_OVERRIDE.set(locale.map(str::to_owned));\n\
         }\n\n",
    );
    render_app_id(&mut out, brand);
    render_locale_list(&mut out, catalog);
    render_locale_resolver(&mut out, catalog);
    render_language_names(&mut out, catalog);
    for message in &catalog.messages {
        render_message(&mut out, catalog, message);
    }
    out
}

/// Emits `language_name`, the Rust member of the endonym accessor every client's language picker
/// labels its rows with.
///
/// The other targets resolve a `settings_language_<code>` key at runtime; this one has no lookup
/// table, so the dispatch is generated. Codegen already fails when a locale carries no such key,
/// which is what makes every arm here safe to write.
fn render_language_names(out: &mut String, catalog: &Catalog) {
    out.push_str(
        "/// The endonym for a shipped locale (\"Nederlands\" for \"nl\"). An unknown code yields\n\
         /// the code itself.\n\
         pub(crate) fn language_name(code: &str) -> String {\n\
             match code {\n",
    );
    for locale in ordered_locales(catalog) {
        writeln!(
            out,
            "        {locale:?} => settings_language_{locale}().to_owned(),"
        )
        .expect("writing to String cannot fail");
    }
    out.push_str("        other => other.to_owned(),\n    }\n}\n\n");
}

/// The catalog's locales with the base first, so a picker built from the list opens on it.
fn ordered_locales(catalog: &Catalog) -> Vec<String> {
    let mut ordered = vec![catalog.base.clone()];
    ordered.extend(
        catalog
            .locales
            .iter()
            .filter(|locale| *locale != &catalog.base)
            .cloned(),
    );
    ordered
}

/// Emits the application id this build was branded with (`docs/branding.md`).
///
/// The Linux client needs it at runtime: the GTK application id, the libsecret schema, the
/// user-data directory a Flatpak gets, and has no bundle to ask, so it is compiled in. It rides
/// with the catalog because this generator already resolves the brand for the name substitution;
/// a second reader in a `build.rs` would be a second answer to the same question.
fn render_app_id(out: &mut String, brand: &Brand) {
    let _ = write!(
        out,
        "/// The reverse-DNS id this build was branded with: the GTK application id, the\n\
         /// libsecret schema, and the `~/.var/app/<id>` a Flatpak keeps its data in.\n\
         pub(crate) const APP_ID: &str = {:?};\n\n",
        brand.id
    );
}

/// Emits the catalog's locale list: the Rust member of the `L10n.locales` / `LOCALES` / `Locales`
/// family every client reads instead of hand-keeping its own.
///
/// A hand-kept list is how the Windows launcher stayed at `en|nl` through five added languages
/// while every other path grew to seven, and nothing said so. The base locale leads, so a picker
/// built from this renders English first without a second rule deciding order.
fn render_locale_list(out: &mut String, catalog: &Catalog) {
    let ordered = ordered_locales(catalog);
    writeln!(
        out,
        "pub(crate) const LOCALES: [&str; {}] = {:?};\n",
        ordered.len(),
        ordered
    )
    .expect("writing to String cannot fail");
}

fn render_locale_resolver(out: &mut String, catalog: &Catalog) {
    out.push_str(
        "pub(crate) fn active_locale() -> &'static str {\n\
             static LOCALE: OnceLock<&'static str> = OnceLock::new();\n\
             LOCALE.get_or_init(|| {\n\
                 let raw = LOCALE_OVERRIDE\n\
                     .get()\n\
                     .and_then(Clone::clone)\n\
                     .or_else(sys_locale::get_locale)\n\
                     .unwrap_or_default();\n\
                 let language = raw\n\
                     .split(['-', '_', '.'])\n\
                     .next()\n\
                     .unwrap_or_default()\n\
                     .to_ascii_lowercase();\n\
                 match language.as_str() {\n",
    );
    for locale in &catalog.locales {
        if locale != &catalog.base {
            writeln!(out, "            {locale:?} => {locale:?},")
                .expect("writing to String cannot fail");
        }
    }
    writeln!(
        out,
        "            _ => {:?},\n        }}\n    }})\n}}\n",
        catalog.base
    )
    .expect("writing to String cannot fail");
}

fn render_message(out: &mut String, catalog: &Catalog, message: &Message) {
    let return_type = if message.placeholders.is_empty() {
        "&'static str"
    } else {
        "String"
    };
    let params = message
        .placeholders
        .iter()
        .map(|name| format!("{name}: {}", rust_type(param_type(name))))
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        out,
        "pub(crate) fn {}({params}) -> {return_type} {{",
        message.key
    )
    .expect("writing to String cannot fail");
    if message.placeholders.is_empty() {
        render_template_match(out, catalog, message, 4);
    } else {
        out.push_str("    let mut message = ");
        render_template_match(out, catalog, message, 4);
        out.push_str("        .to_owned();\n");
        for placeholder in &message.placeholders {
            let replacement = match param_type(placeholder) {
                ParamType::Int => format!("&{placeholder}.to_string()"),
                ParamType::Str => placeholder.clone(),
            };
            writeln!(
                out,
                "    message = message.replace({:?}, {replacement});",
                format!("{{{placeholder}}}")
            )
            .expect("writing to String cannot fail");
        }
        out.push_str("    message\n");
    }
    out.push_str("}\n\n");
}

fn render_template_match(out: &mut String, catalog: &Catalog, message: &Message, indent: usize) {
    let spaces = " ".repeat(indent);
    let base_value = &message.values[&catalog.base];
    let has_override = catalog
        .locales
        .iter()
        .any(|locale| locale != &catalog.base && &message.values[locale] != base_value);
    if !has_override {
        writeln!(out, "{spaces}{base_value:?}").expect("writing to String cannot fail");
        return;
    }

    writeln!(out, "{spaces}match active_locale() {{").expect("writing to String cannot fail");
    for locale in &catalog.locales {
        if locale != &catalog.base && &message.values[locale] != base_value {
            let value = &message.values[locale];
            writeln!(out, "{spaces}    {locale:?} => {value:?},")
                .expect("writing to String cannot fail");
        }
    }
    writeln!(out, "{spaces}    _ => {base_value:?},\n{spaces}}}")
        .expect("writing to String cannot fail");
}

const fn rust_type(param: ParamType) -> &'static str {
    match param {
        ParamType::Int => "i64",
        ParamType::Str => "&str",
    }
}
