//! Build-time localisation codegen for the native clients.
//!
//! Reads the shared inlang message catalog (`messages/<locale>.json` + `project.inlang/
//! settings.json`, the same format the Allodia web app uses), validates it, and emits a
//! per-platform native artifact plus a typed accessor:
//!
//! - **swift**; `L10n.swift` (typed accessor + embedded tables) for the macOS client.
//! - **kotlin**; `res/values[-<locale>]/strings.xml` + `L10n.kt` for the Android client.
//! - **winui**; `Strings/<locale>/Resources.resw` + `L10n.cs` for the Windows client.
//! - **rust**; `l10n.rs` (typed accessor + embedded tables) for the Linux client.
//!
//! The generated files are build artifacts (gitignored, regenerated by each client's build
//! script, exactly like the UniFFI bindings); the JSON catalog is the checked-in source.
//!
//! It also carries the app's identity into the clients (`docs/branding.md`): `{app_name}` in the
//! catalog becomes whatever the build was branded as, and the Rust and WinUI targets get the
//! application id as a constant. Both because this is already the one build step every client
//! runs: a separate reader per client would be a separate answer to the same question.

use std::path::{Path, PathBuf};

mod brand;
mod emit_kotlin;
mod emit_rust;
mod emit_swift;
mod emit_winui;
pub mod model;
mod parse;
mod validate;

pub use model::Catalog;

/// A codegen target platform.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Target {
    /// macOS / Swift (`L10n.swift`).
    Swift,
    /// Android / Kotlin (`strings.xml` + `L10n.kt`).
    Kotlin,
    /// Windows / WinUI 3 (`Resources.resw` + `L10n.cs`).
    Winui,
    /// Linux / Rust (`l10n.rs`).
    Rust,
}

impl Target {
    /// Parses a `--target` value (`swift` | `kotlin` | `winui` | `rust`).
    ///
    /// # Errors
    ///
    /// Returns a message naming the accepted values when `s` is not one of them.
    pub fn parse(s: &str) -> Result<Self, String> {
        match s {
            "swift" => Ok(Self::Swift),
            "kotlin" => Ok(Self::Kotlin),
            "winui" => Ok(Self::Winui),
            "rust" => Ok(Self::Rust),
            other => Err(format!(
                "unknown target \"{other}\" (expected swift|kotlin|winui|rust)"
            )),
        }
    }
}

/// Loads + validates the catalog under `root`, then emits `target` into `out` (creating
/// directories as needed). `package` is the Kotlin package / C# namespace for the typed
/// accessor, it is ignored for the Swift and Rust targets. Returns every file the target
/// covers, each saying whether this run changed it on disk.
///
/// # Errors
///
/// Returns a message if the catalog cannot be loaded, fails validation, or a file cannot be
/// written.
pub fn generate(
    target: Target,
    root: &Path,
    out: &Path,
    package: &str,
) -> Result<Vec<Generated>, String> {
    let mut raw = parse::load(root)?;
    let brand = brand::resolve(root)?;
    // Before validation, so `{app_name}` is never seen as a message parameter: the product's own
    // name is a build-time constant, not something a call site passes (docs/branding.md).
    brand::replace_app_name(&mut raw, &brand.name);
    validate::check(&raw)?;
    let catalog = Catalog::from_raw(&raw);
    let files = match target {
        Target::Swift => emit_swift::render(&catalog, &brand),
        Target::Kotlin => emit_kotlin::render(&catalog, package),
        Target::Winui => emit_winui::render(&catalog, package, &brand),
        Target::Rust => emit_rust::render(&catalog, &brand),
    };
    write_files(out, files)
}

/// One file the catalog emits, and whether this run changed it on disk.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Generated {
    /// Where the file lives.
    pub path: PathBuf,
    /// `false` when the file was already byte-identical and was left untouched.
    pub rewritten: bool,
}

fn write_files(base: &Path, files: Vec<(String, String)>) -> Result<Vec<Generated>, String> {
    let mut written = Vec::new();
    for (rel, content) in files {
        let path = base.join(&rel);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|e| format!("{}: {e}", parent.display()))?;
        }
        // Rewriting a byte-identical file still moves its mtime, and the client builds this feeds
        // decide what to recompile from mtimes alone: MSBuild rebuilds the WinUI app, xcodebuild
        // the Swift one. Leave an unchanged file alone so a build that changed nothing has nothing
        // to do. (An unreadable or absent file simply reads as "different" and gets written.)
        let unchanged = std::fs::read(&path).is_ok_and(|old| old == content.as_bytes());
        if !unchanged {
            std::fs::write(&path, content).map_err(|e| format!("{}: {e}", path.display()))?;
        }
        written.push(Generated {
            path,
            rewritten: !unchanged,
        });
    }
    Ok(written)
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use super::{
        Target,
        brand::Brand,
        emit_kotlin, emit_rust, emit_swift, emit_winui,
        model::{Catalog, Raw, placeholders},
        validate, write_files,
    };

    fn raw() -> Raw {
        // Every locale carries its own picker label (`settings_language_<loc>`); `validate`
        // requires it, since the clients build the language picker from the catalog.
        let en = [
            ("greeting", "Hi {name}"),
            ("unread", "{count} unread"),
            ("settings", "Settings"),
            ("settings_language_en", "English"),
            ("settings_language_nl", "Nederlands"),
        ];
        let nl = [
            ("greeting", "Hoi {name}"),
            ("unread", "{count} ongelezen"),
            ("settings", "Instellingen"),
            ("settings_language_en", "English"),
            ("settings_language_nl", "Nederlands"),
        ];
        let mut maps = BTreeMap::new();
        maps.insert("en".to_string(), to_map(&en));
        maps.insert("nl".to_string(), to_map(&nl));
        Raw {
            base: "en".to_string(),
            locales: vec!["en".to_string(), "nl".to_string()],
            maps,
        }
    }

    fn fixture_brand() -> Brand {
        Brand {
            name: "Fixture Mail".to_string(),
            id: "org.fixture.client".to_string(),
        }
    }

    fn to_map(pairs: &[(&str, &str)]) -> BTreeMap<String, String> {
        pairs
            .iter()
            .map(|(k, v)| ((*k).to_string(), (*v).to_string()))
            .collect()
    }

    #[test]
    fn regenerating_identical_content_leaves_the_file_untouched() {
        // Every client build downstream of this decides what to recompile from mtimes, so a
        // byte-identical rewrite costs a full rebuild of the WinUI app for no reason.
        let dir = std::env::temp_dir().join("mailcal-l10n-unchanged-file-test");
        let _ = std::fs::remove_dir_all(&dir);
        let resw = || {
            vec![(
                "Strings/en/Resources.resw".to_string(),
                "<root/>".to_string(),
            )]
        };

        let first = write_files(&dir, resw()).expect("the first pass creates the file");
        assert!(
            first[0].rewritten,
            "a file that did not exist yet is written"
        );
        let stamp = std::fs::metadata(&first[0].path)
            .and_then(|m| m.modified())
            .expect("the written file has a modification time");

        let again = write_files(&dir, resw()).expect("a second identical pass succeeds");
        assert!(
            !again[0].rewritten,
            "identical content must not be rewritten"
        );
        assert_eq!(
            std::fs::metadata(&again[0].path)
                .and_then(|m| m.modified())
                .ok(),
            Some(stamp),
            "the file's modification time must survive an identical pass"
        );

        let edited = vec![(
            "Strings/en/Resources.resw".to_string(),
            "<root>x</root>".to_string(),
        )];
        let changed = write_files(&dir, edited).expect("changed content is written");
        assert!(changed[0].rewritten, "changed content is written");
        assert_eq!(
            std::fs::read_to_string(&changed[0].path).expect("the file reads back"),
            "<root>x</root>"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn valid_catalog_passes() {
        assert!(validate::check(&raw()).is_ok());
    }

    #[test]
    fn missing_key_fails() {
        let mut r = raw();
        r.maps.get_mut("nl").unwrap().remove("settings");
        let err = validate::check(&r).unwrap_err();
        assert!(err.contains("missing key \"settings\""), "{err}");
    }

    #[test]
    fn extra_key_fails() {
        let mut r = raw();
        r.maps
            .get_mut("nl")
            .unwrap()
            .insert("bonus".to_string(), "x".to_string());
        let err = validate::check(&r).unwrap_err();
        assert!(err.contains("unknown key \"bonus\""), "{err}");
    }

    #[test]
    fn placeholder_mismatch_fails() {
        let mut r = raw();
        r.maps
            .get_mut("nl")
            .unwrap()
            .insert("greeting".to_string(), "Hoi {naam}".to_string());
        let err = validate::check(&r).unwrap_err();
        assert!(err.contains("placeholders"), "{err}");
    }

    #[test]
    fn bad_identifier_fails() {
        let mut r = raw();
        for loc in ["en", "nl"] {
            r.maps
                .get_mut(loc)
                .unwrap()
                .insert("bad.key".to_string(), "x".to_string());
        }
        let err = validate::check(&r).unwrap_err();
        assert!(err.contains("not a valid identifier"), "{err}");
    }

    #[test]
    fn locale_without_a_picker_label_fails() {
        let mut r = raw();
        r.locales.push("de".to_string());
        r.maps.insert("de".to_string(), r.maps["nl"].clone());
        let err = validate::check(&r).unwrap_err();
        assert!(
            err.contains("missing key \"settings_language_de\""),
            "{err}"
        );
    }

    #[test]
    fn each_target_emits_the_catalog_locales_and_endonyms() {
        let catalog = Catalog::from_raw(&raw());

        let swift = &emit_swift::render(&catalog, &fixture_brand())[0].1;
        assert!(swift.contains("public static let locales = [\"en\", \"nl\"]"));
        assert!(swift.contains("public static func languageName(_ code: String) -> String"));

        let files = emit_kotlin::render(&catalog, "eu.allodia.mailcal");
        let kt = &files
            .iter()
            .find(|(p, _)| p.ends_with("L10n.kt"))
            .unwrap()
            .1;
        assert!(kt.contains("val LOCALES = listOf(\"en\", \"nl\")"));
        assert!(kt.contains("\"nl\" -> settings_language_nl(ctx)"));

        let files = emit_winui::render(&catalog, "Allodia.Mailcal", &fixture_brand());
        let cs = &files.iter().find(|(p, _)| p == "L10n.cs").unwrap().1;
        assert!(cs.contains(
            "public static string LanguageName(string code) => Get(\"settings_language_\" + code);"
        ));
        // The locale list is a SEPARATE file, and must stay one: `Mailcal.Tests` is a plain
        // net10.0 assembly and links it to pin `AppCulture`, so anything MRT-Core landing in it
        // breaks that build. Assert both halves: the list is there, and it arrives without the
        // resource `using` that `L10n.cs` opens with.
        let locales = &files.iter().find(|(p, _)| p == "L10nLocales.cs").unwrap().1;
        assert!(locales.contains("public static readonly string[] Locales = [\"en\", \"nl\"];"));
        assert!(
            !locales.contains("Microsoft.Windows.ApplicationModel.Resources"),
            "the locale list must not drag MRT-Core into the WinUI-free test assembly"
        );
        assert!(
            !cs.contains("string[] Locales"),
            "the list lives in one file"
        );

        // Rust was the one target without a list, and the Linux settings picker hand-kept
        // `en`/`nl` in its place: the same two-language stall this test was written to catch on
        // Windows, in the target the test did not cover.
        let rs = &emit_rust::render(&catalog, &fixture_brand())[0].1;
        assert!(rs.contains("pub(crate) const LOCALES: [&str; 2] = [\"en\", \"nl\"]"));
        assert!(
            rs.contains("pub(crate) fn active_locale()"),
            "the resolved locale is part of the emitted API; showcase mode seeds its sample \
             content from it"
        );
    }

    #[test]
    fn placeholders_dedupe_in_first_appearance_order() {
        assert_eq!(
            placeholders("{a} {b} then {a} again"),
            vec!["a".to_string(), "b".to_string()]
        );
    }

    #[test]
    fn swift_emits_typed_accessors_and_tables() {
        let files = emit_swift::render(&Catalog::from_raw(&raw()), &fixture_brand());
        let src = &files[0];
        assert_eq!(src.0, "L10n.swift");
        // A constant, not `Bundle.main`: MailcalKit is compiled and tested by SwiftPM outside any
        // app bundle, where `Bundle.main` is the test runner rather than the app.
        let brand = files.iter().find(|(p, _)| p == "Brand.swift").unwrap();
        assert!(
            brand
                .1
                .contains("public static let appID = \"org.fixture.client\"")
        );
        assert!(
            src.1
                .contains("static func greeting(name: String) -> String")
        );
        assert!(src.1.contains("static func unread(count: Int) -> String"));
        assert!(src.1.contains("static func settings() -> String"));
        assert!(src.1.contains("\"Instellingen\""));
        assert!(src.1.contains("Locale.preferredLanguages"));
    }

    #[test]
    fn swift_derives_the_formatting_locale_from_the_resolved_language() {
        // Apple's dates must follow the app's Language setting, and `Locale.current` cannot carry
        // it: the bundle ships no `.lproj`, so the OS resolves the app to English and a Dutch build
        // listed `Mon` under `zo`. `appLocale` is that single source; if this accessor stops being
        // emitted, or stops being fed by `current()`, every Apple date silently reverts to English
        // while the strings around it stay Dutch (docs/timestamps.md).
        let src = &emit_swift::render(&Catalog::from_raw(&raw()), &fixture_brand())[0];
        assert!(
            src.1
                .contains("public static let appLocale = Locale(identifier: current())"),
            "L10n.swift must derive appLocale from the resolved language: {}",
            src.1
        );
    }

    #[test]
    fn kotlin_emits_positional_args_and_accessor() {
        let files = emit_kotlin::render(&Catalog::from_raw(&raw()), "eu.allodia.mailcal");
        let strings = &files
            .iter()
            .find(|(p, _)| p == "res/values/strings.xml")
            .unwrap()
            .1;
        assert!(strings.contains("<string name=\"greeting\">Hi %1$s</string>"));
        assert!(strings.contains("<string name=\"unread\">%1$d unread</string>"));
        let kt = &files
            .iter()
            .find(|(p, _)| p.ends_with("L10n.kt"))
            .unwrap()
            .1;
        assert!(kt.contains("package eu.allodia.mailcal"));
        assert!(kt.contains(
            "fun greeting(ctx: Context, name: String): String = ctx.getString(R.string.greeting, name)"
        ));
        assert!(
            kt.contains("fun settings(ctx: Context): String = ctx.getString(R.string.settings)")
        );
    }

    #[test]
    fn winui_emits_resw_and_accessor() {
        let files = emit_winui::render(
            &Catalog::from_raw(&raw()),
            "Allodia.Mailcal",
            &fixture_brand(),
        );
        let resw = &files
            .iter()
            .find(|(p, _)| p == "Strings/nl/Resources.resw")
            .unwrap()
            .1;
        assert!(resw.contains("<data name=\"greeting\" xml:space=\"preserve\">"));
        assert!(resw.contains("Hoi {0}"));
        let cs = &files.iter().find(|(p, _)| p == "L10n.cs").unwrap().1;
        assert!(cs.contains("namespace Allodia.Mailcal;"));
        assert!(cs.contains(
            "public static string Greeting(string name) => string.Format(Get(\"greeting\"), name);"
        ));
        assert!(cs.contains("public static string Settings() => Get(\"settings\");"));
        // The override plumbing: a context-driven resolver, set via SetLanguage's Language
        // qualifier, so the language switch needs no package identity (works unpackaged).
        assert!(cs.contains("public static void SetLanguage(string language)"));
        assert!(cs.contains("context.QualifierValues[\"Language\"] = language;"));
        assert!(cs.contains("Map.TryGetValue(key, _context)?.ValueAsString"));

        // The application id is its own dependency-free file, for the same reason the locale list
        // is one: `Mailcal.Tests` pins the protocol scheme, the credential prefix and the MCP pipe
        // name, and cannot link anything that reaches MRT-Core.
        let brand = &files.iter().find(|(p, _)| p == "Brand.cs").unwrap().1;
        assert!(brand.contains("public const string AppId = \"org.fixture.client\";"));
        assert!(
            !brand.contains("using "),
            "Brand.cs must stay dependency-free:\n{brand}"
        );
    }

    #[test]
    fn rust_target_parses_and_names_every_supported_target_on_error() {
        assert_eq!(Target::parse("rust"), Ok(Target::Rust));
        let error = Target::parse("browser").expect_err("unsupported target must fail");
        assert!(error.contains("swift|kotlin|winui|rust"), "{error}");
    }

    #[test]
    fn rust_emits_typed_accessors_and_runtime_locale_detection() {
        let files = emit_rust::render(&Catalog::from_raw(&raw()), &fixture_brand());
        assert_eq!(files.len(), 1);
        let (path, source) = &files[0];
        assert_eq!(path, "l10n.rs");
        assert!(source.contains(".or_else(sys_locale::get_locale)"));
        assert!(source.contains("set_locale_override"));
        assert!(source.contains("pub(crate) fn greeting(name: &str) -> String"));
        assert!(source.contains("pub(crate) fn unread(count: i64) -> String"));
        assert!(source.contains("pub(crate) fn settings() -> &'static str"));
        assert!(source.contains("\"Instellingen\""));
        // The Linux client has no bundle to ask what it is called, so the id is compiled in.
        assert!(source.contains("pub(crate) const APP_ID: &str = \"org.fixture.client\";"));
    }

    #[test]
    fn rust_omits_a_locale_arm_when_its_translation_matches_the_base() {
        let mut fixture = raw();
        fixture
            .maps
            .get_mut("nl")
            .expect("Dutch fixture")
            .insert("settings".to_owned(), "Settings".to_owned());

        let files = emit_rust::render(&Catalog::from_raw(&fixture), &fixture_brand());
        let source = &files[0].1;

        assert!(!source.contains("\"nl\" => \"Settings\""));
    }
}
