//! Build-time localisation codegen for the native clients.
//!
//! Reads the shared inlang message catalog (`messages/<locale>.json` + `project.inlang/
//! settings.json`, the same format the Allodia web app uses), validates it, and emits a
//! per-platform native artifact plus a typed accessor:
//!
//! - **swift**; `L10n.swift` (typed accessor + embedded tables) for the macOS client.
//! - **kotlin**; `res/values[-<locale>]/strings.xml` + `L10n.kt` for the Android client.
//! - **winui**; `Strings/<locale>/Resources.resw` + `L10n.cs` for the Windows client.
//! - **rust**; `l10n.rs` (typed accessor + embedded tables) for the Linux client.
//!
//! The generated files are build artifacts (gitignored, regenerated by each client's build
//! script, exactly like the UniFFI bindings); the JSON catalog is the checked-in source.
//!
//! # Plural forms
//!
//! A key may carry a singular partner, `<key>_one` beside `<key>`, both keeping the `{count}`
//! (`"mailbox_count_conversations_one": "{count} conversation"`). The two fold into **one**
//! accessor that picks the form the active locale's grammar asks for, and the partner gets none
//! of its own: a caller passes a count, never a grammatical form, so the four clients cannot
//! disagree about the rule. A key with no partner is emitted exactly as before.
//!
//! French takes the singular at **zero** as well as one; every other locale shipped here (en, nl,
//! de, es, it, pt-PT) takes it at one alone. Both are CLDR's rule for the language, and zero
//! matters because an empty folder still states its count.
//!
//! ⚠️ **The `{count}` is what makes it a plural form.** Older pairs here spell the numeral into
//! the sentence instead (`"invitation_attendees_one": "1 attendee"`), making them two messages a
//! *call site* chooses between; those keep their own accessors. A partner written `"1
//! conversation"` would quietly get that older behaviour, and its plural would go on printing
//! "1 conversations".
//!
//! It also carries the app's identity into the clients (`docs/branding.md`): `{app_name}` in the
//! catalog becomes whatever the build was branded as, and the Rust and WinUI targets get the
//! application id as a constant. Both because this is already the one build step every client
//! runs: a separate reader per client would be a separate answer to the same question.

use std::path::{Path, PathBuf};

mod brand;
mod emit_kotlin;
mod emit_rust;
mod emit_swift;
mod emit_winui;
pub mod model;
mod parse;
mod validate;

pub use model::Catalog;

/// A codegen target platform.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Target {
    /// macOS / Swift (`L10n.swift`).
    Swift,
    /// Android / Kotlin (`strings.xml` + `L10n.kt`).
    Kotlin,
    /// Windows / WinUI 3 (`Resources.resw` + `L10n.cs`).
    Winui,
    /// Linux / Rust (`l10n.rs`).
    Rust,
}

impl Target {
    /// Parses a `--target` value (`swift` | `kotlin` | `winui` | `rust`).
    ///
    /// # Errors
    ///
    /// Returns a message naming the accepted values when `s` is not one of them.
    pub fn parse(s: &str) -> Result<Self, String> {
        match s {
            "swift" => Ok(Self::Swift),
            "kotlin" => Ok(Self::Kotlin),
            "winui" => Ok(Self::Winui),
            "rust" => Ok(Self::Rust),
            other => Err(format!(
                "unknown target \"{other}\" (expected swift|kotlin|winui|rust)"
            )),
        }
    }
}

/// Loads + validates the catalog under `root`, then emits `target` into `out` (creating
/// directories as needed). `package` is the Kotlin package / C# namespace for the typed
/// accessor, it is ignored for the Swift and Rust targets. Returns every file the target
/// covers, each saying whether this run changed it on disk.
///
/// # Errors
///
/// Returns a message if the catalog cannot be loaded, fails validation, or a file cannot be
/// written.
pub fn generate(
    target: Target,
    root: &Path,
    out: &Path,
    package: &str,
) -> Result<Vec<Generated>, String> {
    let mut raw = parse::load(root)?;
    let brand = brand::resolve(root)?;
    // Before validation, so `{app_name}` is never seen as a message parameter: the product's own
    // name is a build-time constant, not something a call site passes (docs/branding.md).
    brand::replace_app_name(&mut raw, &brand.name);
    validate::check(&raw)?;
    let catalog = Catalog::from_raw(&raw);
    let files = match target {
        Target::Swift => emit_swift::render(&catalog, &brand),
        Target::Kotlin => emit_kotlin::render(&catalog, package),
        Target::Winui => emit_winui::render(&catalog, package, &brand),
        Target::Rust => emit_rust::render(&catalog, &brand),
    };
    write_files(out, files)
}

/// One file the catalog emits, and whether this run changed it on disk.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Generated {
    /// Where the file lives.
    pub path: PathBuf,
    /// `false` when the file was already byte-identical and was left untouched.
    pub rewritten: bool,
}

fn write_files(base: &Path, files: Vec<(String, String)>) -> Result<Vec<Generated>, String> {
    let mut written = Vec::new();
    for (rel, content) in files {
        let path = base.join(&rel);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|e| format!("{}: {e}", parent.display()))?;
        }
        // Rewriting a byte-identical file still moves its mtime, and the client builds this feeds
        // decide what to recompile from mtimes alone: MSBuild rebuilds the WinUI app, xcodebuild
        // the Swift one. Leave an unchanged file alone so a build that changed nothing has nothing
        // to do. (An unreadable or absent file simply reads as "different" and gets written.)
        let unchanged = std::fs::read(&path).is_ok_and(|old| old == content.as_bytes());
        if !unchanged {
            std::fs::write(&path, content).map_err(|e| format!("{}: {e}", path.display()))?;
        }
        written.push(Generated {
            path,
            rewritten: !unchanged,
        });
    }
    Ok(written)
}

#[cfg(test)]
#[path = "plural_tests.rs"]
mod plural_tests;

#[cfg(test)]
#[path = "lib_tests.rs"]
mod tests;
