//! Relm4 input messages for the Linux shell.

use std::{fmt, path::PathBuf};

use mailcal_bindings::{
    AgentDraft, ContactDetail, MailtoPrefill, SearchScope, SetupRecommendation, Surface,
};

use super::{
    allodia::AllodiaOutcome,
    allodia_sync::AllodiaSyncOutcome,
    calendar::{CalendarMode, CreateSlot, EventForm, EventIdentity},
    composer_model::ComposerSubmission,
    folder_pane::SidebarTarget,
    google::GoogleOutcome,
    invitation::InvitationAnswer,
    jmap::{JmapOutcome, JmapPrepared, JmapReauthOutcome, JmapReauthPrepared},
    mail_actions::{ActionKind, MailActionRequest, MessageTarget},
    mailbox::ThreadKey,
    microsoft::MicrosoftOutcome,
    model::OpenedMessage,
    setup_model::{AccountSubmission, ManualForm},
};

pub(crate) enum AppInput {
    RefreshRequested,
    RetryUnfiledCopy,
    DismissUnfiledCopy,
    RefreshCalendar,
    PeriodicCalendarRefresh,
    SurfaceChanged(Surface),
    NetworkReachabilityChanged(bool),
    CheckDeviceTimeZone,
    AcceptDeviceTimeZone,
    DismissDeviceTimeZone,
    ResolveExpiredSignIn,
    ResolveMailReauth,
    ResolveCalendarReauth,
    ShowMail,
    ShowCalendar,
    ShowContacts,
    RefreshContacts,
    SearchContacts(String),
    OpenContact(String),
    /// One detail lookup's answer, tagged with the lookup it belongs to so a slower earlier one
    /// cannot land on top of the person the user opened since. `None` means the person is gone.
    ContactOpened(u64, Option<Box<ContactDetail>>),
    SetCalendarMode(CalendarMode),
    StepCalendar(i32),
    CalendarToday,
    ManageCalendars,
    ShowCalendarDay(String),
    ToggleAllDay,
    OpenCalendarEvent(EventIdentity),
    BeginNewEvent,
    BeginNewEventAt(CreateSlot),
    BeginEditEvent,
    /// The editor's Save, with which occurrences the user said it meant: `true` splits an
    /// override out of the series, `false` rewrites the series itself (and is the only thing an
    /// editor opened on the series can mean).
    SubmitEventForm(Box<EventForm>, bool),
    RequestDeleteEvent(EventIdentity),
    RequestDeleteCurrentEvent,
    DeleteCalendarEvent(EventIdentity),
    DismissCalendarDialog,
    /// What is in the mail-search field. Empty leaves search, which the core answers by
    /// restoring the account and folder the search was opened from.
    SearchMail(String),
    SetSearchScope(SearchScope),
    /// The horizon line's route to the setting that decides how far back a search can reach.
    OpenSyncDepthSettings,
    OpenThreadMessage(Box<OpenedMessage>),
    SetThreadExpanded {
        thread: ThreadKey,
        expanded: bool,
    },
    PerformMailAction(Box<MailActionRequest>),
    PerformOpenedMailAction(ActionKind),
    RequestPermanentDelete(MessageTarget),
    DismissPermanentDelete,
    ArchiveThread {
        account: String,
        thread_id: String,
    },
    ActivateSidebar(SidebarTarget),
    SetAccountExpanded {
        account: String,
        expanded: bool,
    },
    /// Answer the invitation the open message carries. The **message** is named where this is
    /// dispatched, never the event: the answer goes out as the address the invitation matched,
    /// and only the core knows the address set (`docs/invitations.md` §4).
    RespondToInvitation(Box<InvitationAnswer>),
    /// Answer the standing "the organiser wasn't told" question. Carries no handle on the meeting,
    /// the core holds the question and clears it as this arrives, so pressing twice cannot email
    /// the organiser twice.
    AnswerReplyPrompt {
        send: bool,
        remember: bool,
        reply_subject: String,
    },
    LoadRemoteImages,
    RetryOpen,
    OpenMailto(Box<MailtoPrefill>),
    OpenAgentDraft(Box<AgentDraft>),
    BeginNew,
    BeginReply(bool),
    BeginForward,
    CancelComposer,
    /// The open draft's answer to "would anything be lost?": see [`super::composer_draft`].
    ComposerDraftChecked(bool),
    /// Throw the draft away and take the navigation that was waiting on it.
    DiscardDraft,
    /// Keep the draft, and drop the navigation that was waiting on it.
    KeepEditing,
    SubmitComposer(Box<ComposerSubmission>),
    SaveAttachment {
        id: u32,
        destination: PathBuf,
    },
    OpenAttachment {
        id: u32,
        file_name: String,
    },
    AttachmentSaved(bool),
    AttachmentDecoded(Result<PathBuf, ()>),
    /// The desktop refused to open a decoded attachment; the portal's answer, which arrives
    /// after the launch rather than from it.
    AttachmentOpenFailed,
    WebViewReady,
    WebViewUnavailable,
    OpenSettings,
    OpenAccountSetup,
    RestartAccountSetup,
    CancelAccountSetup,
    ManualAccountSetup(String),
    EditDetectedManually,
    SelectAccountKind(Box<ManualForm>),
    ProbeManualJmapSignIn(Box<ManualForm>),
    DetectAccount(String),
    AccountDetected(String, Box<SetupRecommendation>),
    JmapOAuthAvailable {
        email: String,
        server_url: String,
        available: bool,
    },
    SubmitAccount(Box<AccountSubmission>),
    AccountAdded(Result<(), String>),
    StartGoogleLogin(String),
    CancelGoogleLogin,
    GoogleCallbackReceived(u64),
    GoogleFinished(u64, GoogleOutcome),
    StartMicrosoftLogin(String),
    CancelMicrosoftLogin,
    MicrosoftCallbackReceived(u64),
    MicrosoftFinished(u64, MicrosoftOutcome),
    StartJmapLogin(String, String),
    CancelJmapLogin,
    JmapPrepared(u64, Result<Box<JmapPrepared>, String>),
    JmapCallbackReceived(u64),
    JmapFinished(u64, JmapOutcome),
    JmapReauthPrepared(u64, Result<Box<JmapReauthPrepared>, String>),
    JmapReauthFinished(u64, JmapReauthOutcome),
    ReplaceAccountSecret {
        account: String,
        secret: String,
    },
    AccountSecretReplaced {
        account: String,
        success: bool,
    },
    StartAllodiaSignIn,
    StartAllodiaRegistration,
    ManageAllodiaAccount,
    CancelAllodiaSignIn,
    /// The browser hop for this attempt has outlasted the card's threshold, so the
    /// first-run card owes the person a way back ([`super::setup_onboarding`]).
    AllodiaSignInSlow(u64),
    AllodiaSignInFinished(u64, AllodiaOutcome),
    SignOutOfAllodia,
    /// Ask the account service what the person's other devices hold, and tell it what this one
    /// holds. Emitted at boot and after a sign-in; never by a timer.
    SyncAllodiaAccounts,
    AllodiaSyncFinished(AllodiaSyncOutcome),
    /// Move one account to a sync position.
    SetAllodiaAccountSyncMode(String, mailcal_bindings::AllodiaAccountSyncMode),
    AllodiaSyncModeChanged(String, Option<String>),
    /// Re-read how each account is shared, after the account list changed.
    ReadAccountsSynced,
    /// The Settings sidebar moved to a page. Records it so a later redraw rebuilds on the
    /// page the person is looking at rather than the one the model last named.
    SettingsCategoryShown(crate::ui::settings::Category),
    /// Set up an account one of the person's other devices offered, on the route its record
    /// names rather than one re-derived from the address.
    SetUpOfferedAccount(Box<mailcal_bindings::AllodiaAccountOffer>),
    RemoveAccount(String),
    AccountRemoved(Result<(), String>),
    AnalyticsDecided(bool),
    CollectNewMail,
    BackgroundFinished,
}

impl fmt::Debug for AppInput {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(match self {
            Self::RefreshRequested => "RefreshRequested",
            Self::RetryUnfiledCopy => "RetryUnfiledCopy",
            Self::DismissUnfiledCopy => "DismissUnfiledCopy",
            Self::RefreshCalendar => "RefreshCalendar",
            Self::PeriodicCalendarRefresh => "PeriodicCalendarRefresh",
            Self::SurfaceChanged(_) => "SurfaceChanged",
            Self::NetworkReachabilityChanged(_) => "NetworkReachabilityChanged",
            Self::CheckDeviceTimeZone => "CheckDeviceTimeZone",
            Self::AcceptDeviceTimeZone => "AcceptDeviceTimeZone",
            Self::DismissDeviceTimeZone => "DismissDeviceTimeZone",
            Self::ResolveExpiredSignIn => "ResolveExpiredSignIn",
            Self::ResolveMailReauth => "ResolveMailReauth",
            Self::ResolveCalendarReauth => "ResolveCalendarReauth",
            Self::ShowMail => "ShowMail",
            Self::ShowCalendar => "ShowCalendar",
            Self::ShowContacts => "ShowContacts",
            Self::RefreshContacts => "RefreshContacts",
            Self::SearchContacts(_) => "SearchContacts",
            Self::OpenContact(_) => "OpenContact",
            Self::ContactOpened(..) => "ContactOpened",
            Self::SetCalendarMode(_) => "SetCalendarMode",
            Self::StepCalendar(_) => "StepCalendar",
            Self::CalendarToday => "CalendarToday",
            Self::ManageCalendars => "ManageCalendars",
            Self::ShowCalendarDay(_) => "ShowCalendarDay",
            Self::ToggleAllDay => "ToggleAllDay",
            Self::OpenCalendarEvent(_) => "OpenCalendarEvent",
            Self::BeginNewEvent => "BeginNewEvent",
            Self::BeginNewEventAt(_) => "BeginNewEventAt",
            Self::BeginEditEvent => "BeginEditEvent",
            Self::SubmitEventForm(..) => "SubmitEventForm",
            Self::RequestDeleteEvent(_) => "RequestDeleteEvent",
            Self::RequestDeleteCurrentEvent => "RequestDeleteCurrentEvent",
            Self::DeleteCalendarEvent(_) => "DeleteCalendarEvent",
            Self::DismissCalendarDialog => "DismissCalendarDialog",
            Self::SearchMail(_) => "SearchMail",
            Self::SetSearchScope(_) => "SetSearchScope",
            Self::OpenSyncDepthSettings => "OpenSyncDepthSettings",
            Self::OpenThreadMessage(_) => "OpenThreadMessage",
            Self::SetThreadExpanded { .. } => "SetThreadExpanded",
            Self::PerformMailAction(_) => "PerformMailAction",
            Self::PerformOpenedMailAction(_) => "PerformOpenedMailAction",
            Self::RequestPermanentDelete(_) => "RequestPermanentDelete",
            Self::DismissPermanentDelete => "DismissPermanentDelete",
            Self::ArchiveThread { .. } => "ArchiveThread",
            Self::ActivateSidebar(_) => "ActivateSidebar",
            Self::SetAccountExpanded { .. } => "SetAccountExpanded",
            Self::RespondToInvitation(_) => "RespondToInvitation",
            Self::AnswerReplyPrompt { .. } => "AnswerReplyPrompt",
            Self::LoadRemoteImages => "LoadRemoteImages",
            Self::RetryOpen => "RetryOpen",
            Self::OpenMailto(_) => "OpenMailto",
            Self::OpenAgentDraft(_) => "OpenAgentDraft",
            Self::BeginNew => "BeginNew",
            Self::BeginReply(_) => "BeginReply",
            Self::BeginForward => "BeginForward",
            Self::CancelComposer => "CancelComposer",
            Self::ComposerDraftChecked(_) => "ComposerDraftChecked",
            Self::DiscardDraft => "DiscardDraft",
            Self::KeepEditing => "KeepEditing",
            Self::SubmitComposer(_) => "SubmitComposer",
            Self::SaveAttachment { .. } => "SaveAttachment",
            Self::OpenAttachment { .. } => "OpenAttachment",
            Self::AttachmentSaved(_) => "AttachmentSaved",
            Self::AttachmentDecoded(_) => "AttachmentDecoded",
            Self::AttachmentOpenFailed => "AttachmentOpenFailed",
            Self::WebViewReady => "WebViewReady",
            Self::WebViewUnavailable => "WebViewUnavailable",
            Self::OpenSettings => "OpenSettings",
            Self::OpenAccountSetup => "OpenAccountSetup",
            Self::RestartAccountSetup => "RestartAccountSetup",
            Self::CancelAccountSetup => "CancelAccountSetup",
            Self::ManualAccountSetup(_) => "ManualAccountSetup",
            Self::EditDetectedManually => "EditDetectedManually",
            Self::SelectAccountKind(_) => "SelectAccountKind",
            Self::ProbeManualJmapSignIn(_) => "ProbeManualJmapSignIn",
            Self::DetectAccount(_) => "DetectAccount",
            Self::AccountDetected(..) => "AccountDetected",
            Self::JmapOAuthAvailable { .. } => "JmapOAuthAvailable",
            Self::SubmitAccount(_) => "SubmitAccount",
            Self::AccountAdded(_) => "AccountAdded",
            Self::StartGoogleLogin(_) => "StartGoogleLogin",
            Self::CancelGoogleLogin => "CancelGoogleLogin",
            Self::GoogleCallbackReceived(_) => "GoogleCallbackReceived",
            Self::GoogleFinished(..) => "GoogleFinished",
            Self::StartMicrosoftLogin(_) => "StartMicrosoftLogin",
            Self::CancelMicrosoftLogin => "CancelMicrosoftLogin",
            Self::MicrosoftCallbackReceived(_) => "MicrosoftCallbackReceived",
            Self::MicrosoftFinished(..) => "MicrosoftFinished",
            Self::StartJmapLogin(..) => "StartJmapLogin",
            Self::CancelJmapLogin => "CancelJmapLogin",
            Self::JmapPrepared(..) => "JmapPrepared",
            Self::JmapCallbackReceived(_) => "JmapCallbackReceived",
            Self::JmapFinished(..) => "JmapFinished",
            Self::StartAllodiaSignIn => "StartAllodiaSignIn",
            Self::StartAllodiaRegistration => "StartAllodiaRegistration",
            Self::ManageAllodiaAccount => "ManageAllodiaAccount",
            Self::CancelAllodiaSignIn => "CancelAllodiaSignIn",
            Self::AllodiaSignInSlow(_) => "AllodiaSignInSlow",
            Self::AllodiaSignInFinished(..) => "AllodiaSignInFinished",
            Self::SignOutOfAllodia => "SignOutOfAllodia",
            Self::SyncAllodiaAccounts => "SyncAllodiaAccounts",
            Self::AllodiaSyncFinished(_) => "AllodiaSyncFinished",
            Self::SetAllodiaAccountSyncMode(..) => "SetAllodiaAccountSyncMode",
            Self::AllodiaSyncModeChanged(..) => "AllodiaSyncModeChanged",
            Self::ReadAccountsSynced => "ReadAccountsSynced",
            Self::SettingsCategoryShown(_) => "SettingsCategoryShown",
            Self::SetUpOfferedAccount(_) => "SetUpOfferedAccount",
            Self::JmapReauthPrepared(..) => "JmapReauthPrepared",
            Self::JmapReauthFinished(..) => "JmapReauthFinished",
            Self::ReplaceAccountSecret { .. } => "ReplaceAccountSecret",
            Self::AccountSecretReplaced { .. } => "AccountSecretReplaced",
            Self::RemoveAccount(_) => "RemoveAccount",
            Self::AccountRemoved(_) => "AccountRemoved",
            Self::AnalyticsDecided(_) => "AnalyticsDecided",
            Self::CollectNewMail => "CollectNewMail",
            Self::BackgroundFinished => "BackgroundFinished",
        })
    }
}
